### ISSUE TITLE
BuildProject dependency sorting

### ISSUE THREAD

**Issue by tmackenzie01** [tmackenzie01/BootstrapperChecker#1]
Write custom comparer for BuildProject class which uses the first dependency of the project to set the sort order, if first dependency is the same then traverse the dependencies until there is a difference (dependencies of each project are already sorted), if all dependencies are equal then the default is on the name.

**Comment by heymrspaceman** [comment]
Good idea but totally wrong.  I managed to figure it out anyway ;)
